import { Metadata } from "next"
import Footer from "@/components/Footer/footer";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: {
    //absolute: "",
    default: "Next.js Tutorial - Konstantin",
    template: "%s | Konstantin",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header/>        
        {children}
        <Footer/>
      </body>
    </html>
  );
}
